apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: es-replication-cron
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: replicator
            imagePullPolicy: Always
            image: ${IMAGE_NAME}
            env:
            - name: BUCKET_NAME
              value: ${BUCKET_NAME}
            - name: REGION
              value: ap-southeast-1
            - name: REPO_NAME
              value: replication
            - name: ES_URL
              value: ${ES_URL}
            - name: ES_REPLICA
              value: ${ES_REPLICA}
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: honestbee-registry
