apiVersion: batch/v1
kind: Job
metadata:
  name: es-replication
spec:
  template:
    metadata:
      name: es-replication
    spec:
      containers:
      - name: replicator
        imagePullPolicy: Always
        image: ${IMAGE_NAME}
        env:
        - name: BUCKET_NAME
          value: ${BUCKET_NAME}
        - name: REGION
          value: ap-southeast-1
        - name: REPO_NAME
          value: replication
        - name: ES_URL
          value: ${ES_URL}
        - name: ES_REPLICA
          value: ${ES_REPLICA}
      restartPolicy: Never
      imagePullSecrets:
        - name: honestbee-registry
