apiVersion: batch/v1
kind: Job
metadata:
  name: es-replication-${TSTAMP}
spec:
  template:
    metadata:
      name: es-replication
      labels:
        job: es-snapshot-${COMMAND}
    spec:
      containers:
      - name: replicator
        imagePullPolicy: Always
        image: ${IMAGE_NAME}
        env:
        - name: BUCKET_NAME
          value: ${BUCKET_NAME}
        - name: REGION
          value: ap-southeast-1
        - name: API_URL
          value: ${API_URL}
        args: ["${COMMAND}", "--bucket-name", "$(BUCKET_NAME)", "--region", "$(REGION)", "--url", "$(API_URL)"]
      restartPolicy: Never
      imagePullSecrets:
        - name: honestbee-registry
