pipeline:
  publish:
    image: plugins/docker
    repo: quay.io/honestbee/elasticsearch-snapper-snapper
    registry: ${DOCKER_REGISTRY}
    secrets:
      - docker_username
      - docker_password
      - docker_registry
    tags: latest
    when:
      branch: 
        - master
  publish_tags:
    image: plugins/docker
    repo: quay.io/honestbee/elasticsearch-snapper-snapper
    registry: ${DOCKER_REGISTRY}
    secrets:
      - docker_username
      - docker_password
      - docker_registry
    tags: ${DRONE_TAG##v}
    when:
      event:
        - tag
